trading:
  pairs: 
    - USD/ZAR
    - USD/TRY
    - EUR/TRY
    - GBP/ZAR
  timeframe: "1m"
  amount: 50
  max_daily_loss: 5%   # Percentage of account

signals:
  min_confidence: 0.85
  max_trades_per_hour: 12
  required_volume_multiplier: 1.8

telegram:
  channel_id: "@your_channel"
  alert_levels: [BREAKOUT, STRONG, MEDIUM]
